[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "receipt-dynamo-stream"
version = "0.1.0"
dependencies = []

[tool.hatch.build.targets.wheel]
packages = ["receipt_dynamo_stream"]
